function Route(){
    $('.explore-btn').on('click',function(){
        window.location.assign('./index.html');
    });
    $('.myMusic-btn').on('click',function(){
        window.location.assign('./music.html');
    });
    $('.video-btn').on('click',function(){
        window.location.assign('./video.html');
    });
    $('.podacast-btn').on('click',function(){
        window.location.assign('./podacast.html');
    });
    $('.artist-btn').on('click',function(){
        window.location.assign('./artist.html');
    });
    $('.album-btn').on('click',function(){
        window.location.assign('./album.html');
    });
    $('.developer-btn').on('click',function(){
        window.location.assign('./developer.html');
    });
    $('.bug-btn').on('click',function(){
        window.location.assign('./bug.html');
    });
    $('.help-btn').on('click',function(){
        window.location.assign('./help.html');
    });
    $('.file-btn').on('click',function(){
        window.location.assign('./file_Manager.html');
    });
    $('.item-1').on('click',function(){
        window.location.assign('./fileUploade.html');
    })
}